version: '2'

services:
  # build the angular 4 client, mapping source for development and depending on server
  client:
    build: ./ng-client
    volumes: 
      - ./ng-client:/usr/src/app
    ports: 
      - "4200:4200"
  # build the spring boot container, depending on the database    
  server:
    build: ./java-server
    links:
      - db
    ports:
      - "8080:8080"
  # create a mysql database container    
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=welcome1